import { format, parseISO } from 'date-fns';
import type { Expense } from '@/hooks/useExpenses';
import type { Load } from '@/hooks/useLoads';
import { formatCurrency } from '@/lib/loadUtils';

export interface ParkingExportRange {
  label: string;
  from: string; // yyyy-MM-dd
  to: string; // yyyy-MM-dd
}

interface ExportRow {
  date: string;
  amount: number;
  linkedLoad: string;
  notes: string;
}

function buildRows(expenses: Expense[], loads: Load[], range: ParkingExportRange): ExportRow[] {
  const loadsMap = new Map(loads.map((l) => [l.id, l]));
  return expenses
    .filter((e) => e.category === 'Parking')
    .filter((e) => e.expense_date >= range.from && e.expense_date <= range.to)
    .sort((a, b) => a.expense_date.localeCompare(b.expense_date))
    .map((e) => {
      const linked = e.linked_load_id ? loadsMap.get(e.linked_load_id) : null;
      return {
        date: format(parseISO(e.expense_date), 'MM/dd/yyyy'),
        amount: Number(e.amount),
        linkedLoad: linked ? `${linked.pickup_location} → ${linked.dropoff_location}` : '',
        notes: e.notes ?? '',
      };
    });
}

function triggerDownload(blob: Blob, filename: string) {
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  setTimeout(() => URL.revokeObjectURL(url), 100);
}

function escapeCsv(v: string): string {
  if (/[",\n]/.test(v)) return `"${v.replace(/"/g, '""')}"`;
  return v;
}

export function exportParkingCSV(
  expenses: Expense[],
  loads: Load[],
  range: ParkingExportRange,
): { count: number; total: number } {
  const rows = buildRows(expenses, loads, range);
  const total = rows.reduce((s, r) => s + r.amount, 0);

  const header = ['Date', 'Category', 'Amount', 'Linked Load', 'Notes'];
  const lines = [header.join(',')];
  for (const r of rows) {
    lines.push(
      [
        escapeCsv(r.date),
        'Parking',
        r.amount.toFixed(2),
        escapeCsv(r.linkedLoad),
        escapeCsv(r.notes),
      ].join(','),
    );
  }
  lines.push(['', '', total.toFixed(2), 'TOTAL', `${rows.length} entries`].join(','));

  const csv = lines.join('\n');
  const blob = new Blob([csv], { type: 'text/csv;charset=utf-8;' });
  const filename = `parking-expenses_${range.label.replace(/\s+/g, '-').toLowerCase()}_${range.from}_to_${range.to}.csv`;
  triggerDownload(blob, filename);
  return { count: rows.length, total };
}

export async function exportParkingPDF(
  expenses: Expense[],
  loads: Load[],
  range: ParkingExportRange,
  driverName?: string,
): Promise<{ count: number; total: number }> {
  const rows = buildRows(expenses, loads, range);
  const total = rows.reduce((s, r) => s + r.amount, 0);

  // Lazy-load jspdf so it only ships when actually used.
  const [{ default: jsPDF }, autoTableMod] = await Promise.all([
    import('jspdf'),
    import('jspdf-autotable'),
  ]);
  const autoTable = (autoTableMod as { default: (doc: unknown, opts: unknown) => void }).default;

  const doc = new jsPDF({ unit: 'pt', format: 'letter' });

  // Header
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(18);
  doc.text('HaulTrackerPro — Parking Expenses', 40, 50);

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(10);
  doc.setTextColor(100);
  const driverLine = driverName ? `Driver: ${driverName}` : '';
  const rangeLine = `Period: ${format(parseISO(range.from), 'MMM d, yyyy')} – ${format(parseISO(range.to), 'MMM d, yyyy')}`;
  if (driverLine) doc.text(driverLine, 40, 68);
  doc.text(rangeLine, 40, driverLine ? 82 : 68);
  doc.text(`Generated: ${format(new Date(), 'MMM d, yyyy h:mm a')}`, 40, driverLine ? 96 : 82);

  // Table
  autoTable(doc, {
    startY: driverLine ? 116 : 102,
    head: [['Date', 'Amount', 'Linked Load', 'Notes']],
    body: rows.map((r) => [r.date, formatCurrency(r.amount), r.linkedLoad, r.notes]),
    foot: [['', formatCurrency(total), `${rows.length} entries`, 'TOTAL']],
    styles: { fontSize: 9, cellPadding: 6 },
    headStyles: { fillColor: [30, 41, 59], textColor: 255, fontStyle: 'bold' },
    footStyles: { fillColor: [241, 245, 249], textColor: 30, fontStyle: 'bold' },
    columnStyles: {
      0: { cellWidth: 80 },
      1: { cellWidth: 80, halign: 'right' },
    },
    margin: { left: 40, right: 40 },
  });

  // Footer
  const pageHeight = doc.internal.pageSize.getHeight();
  doc.setFontSize(8);
  doc.setTextColor(120);
  doc.text(
    'Submit with load paperwork — generated by HaulTrackerPro',
    40,
    pageHeight - 30,
  );

  const filename = `parking-expenses_${range.label.replace(/\s+/g, '-').toLowerCase()}_${range.from}_to_${range.to}.pdf`;
  doc.save(filename);
  return { count: rows.length, total };
}
