// Branded PDF report builder for HaulTrackerPro.
// Hand-rolled PDF writer (no jsPDF) — keeps bundle small and matches the
// existing exporter style in src/lib/loadUtils.ts.
//
// Design:
//   - Dark navy header band with orange accent rule
//   - White body for print readability
//   - Sectioned tables (Loads, Fuel, Expenses, Tax, Profit)
//   - Footer with haultrackerpro.com + page number
import type { ReportAggregation, ReportType } from '@/lib/reportAggregator';
import { REPORT_TYPE_LABELS } from '@/lib/reportAggregator';
import { TAX_DISCLAIMER } from '@/lib/reportTax';
import { getEffectiveDate } from '@/lib/loadUtils';
import { getLoadExpectedPay, getLoadOperatingMiles } from '@/lib/loadMetrics';
import { format } from 'date-fns';

// ── Page geometry (US Letter) ─────────────────────────────────────────────
const PAGE_W = 612;
const PAGE_H = 792;
const MARGIN_X = 36;
const HEADER_H = 78;
const FOOTER_H = 36;
const BODY_TOP = HEADER_H + 18;
const BODY_BOTTOM = FOOTER_H + 24;

// HaulTrackerPro brand (approximations of the dark-navy + amber theme)
const NAVY = '0.05 0.10 0.18';      // header/footer band
const AMBER = '0.96 0.62 0.04';     // accent / primary
const GREEN = '0.10 0.55 0.30';     // profit positive
const RED = '0.78 0.16 0.16';       // negative / warning
const GREY_LIGHT = '0.94 0.94 0.94';
const GREY_MID = '0.45 0.45 0.45';
const BLACK = '0 0 0';

// ── Helpers ───────────────────────────────────────────────────────────────
// Helvetica (WinAnsi) cannot render most non-ASCII glyphs, AND our PDF
// writer measures /Length and xref offsets in JS string length while the
// Blob is serialized as UTF-8 bytes. Any multi-byte char would corrupt the
// file. So normalize aggressively to printable ASCII before emitting.
function clean(s: string | number | null | undefined, max = 80): string {
  let str = (s == null ? '' : String(s))
    .replace(/[\r\n\t]/g, ' ')
    .replace(/[()\\]/g, ' ')
    .replace(/→|➔|➜/g, '->')
    .replace(/←/g, '<-')
    .replace(/[—–]/g, '-')
    .replace(/…/g, '...')
    .replace(/[‘’]/g, "'")
    .replace(/[“”]/g, '"')
    .replace(/•/g, '*')
    // Drop anything outside printable ASCII
    .replace(/[^\x20-\x7E]/g, '');
  return str.length > max ? str.slice(0, max - 1) + '...' : str;
}
const money = (n: number) =>
  '$' + (Number.isFinite(n) ? n : 0).toLocaleString('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 });
const intStr = (n: number) =>
  (Number.isFinite(n) ? Math.round(n) : 0).toLocaleString('en-US');

// ── Page builder ──────────────────────────────────────────────────────────
type FontWeight = 'F1' | 'F2'; // F1=Helvetica, F2=Helvetica-Bold

class PageBuilder {
  private content = '';
  y = BODY_TOP;

  raw(s: string) { this.content += s + '\n'; }

  fillRect(rgb: string, x: number, y: number, w: number, h: number) {
    this.raw(`${rgb} rg ${x} ${PAGE_H - y - h} ${w} ${h} re f`);
  }
  text(rgb: string, font: FontWeight, size: number, x: number, y: number, str: string) {
    this.raw(`${rgb} rg BT /${font} ${size} Tf ${x} ${PAGE_H - y} Td (${clean(str)}) Tj ET`);
  }

  finalize(): string { return this.content; }
}

function drawHeader(p: PageBuilder, opts: {
  reportTitle: string;
  rangeLabel: string;
  generated: string;
  preparedFor: string;
}) {
  // Navy band
  p.raw(`${NAVY} rg 0 ${PAGE_H - HEADER_H} ${PAGE_W} ${HEADER_H} re f`);
  // Amber accent rule
  p.raw(`${AMBER} rg 0 ${PAGE_H - HEADER_H - 3} ${PAGE_W} 3 re f`);
  // Brand
  p.raw(`1 1 1 rg BT /F2 16 Tf ${MARGIN_X} ${PAGE_H - 28} Td (HaulTrackerPro) Tj ET`);
  p.raw(`${AMBER} rg BT /F1 8 Tf ${MARGIN_X} ${PAGE_H - 42} Td (haultrackerpro.com) Tj ET`);
  // Title + meta (right column)
  p.raw(`1 1 1 rg BT /F2 12 Tf ${MARGIN_X} ${PAGE_H - 60} Td (${clean(opts.reportTitle)}) Tj ET`);
  p.raw(`0.78 0.78 0.78 rg BT /F1 8 Tf ${PAGE_W - MARGIN_X - 250} ${PAGE_H - 28} Td (Date Range: ${clean(opts.rangeLabel)}) Tj ET`);
  p.raw(`0.78 0.78 0.78 rg BT /F1 8 Tf ${PAGE_W - MARGIN_X - 250} ${PAGE_H - 42} Td (Generated: ${clean(opts.generated)}) Tj ET`);
  p.raw(`0.78 0.78 0.78 rg BT /F1 8 Tf ${PAGE_W - MARGIN_X - 250} ${PAGE_H - 56} Td (Prepared For: ${clean(opts.preparedFor, 60)}) Tj ET`);
}

function drawFooter(p: PageBuilder, page: number, totalPages: number) {
  const y = FOOTER_H;
  p.raw(`${NAVY} rg 0 0 ${PAGE_W} ${y} re f`);
  p.raw(`${AMBER} rg 0 ${y} ${PAGE_W} 2 re f`);
  p.raw(`1 1 1 rg BT /F1 8 Tf ${MARGIN_X} 16 Td (Generated by HaulTrackerPro  -  haultrackerpro.com) Tj ET`);
  p.raw(`0.78 0.78 0.78 rg BT /F1 8 Tf ${PAGE_W - MARGIN_X - 60} 16 Td (Page ${page} of ${totalPages}) Tj ET`);
}

// ── Section drawing primitives ────────────────────────────────────────────
function sectionTitle(p: PageBuilder, label: string) {
  ensureSpace(p, 28);
  p.raw(`${AMBER} rg ${MARGIN_X} ${PAGE_H - p.y - 2} 3 14 re f`);
  p.text(BLACK, 'F2', 11, MARGIN_X + 8, p.y + 9, label);
  p.y += 22;
}

function ensureSpace(p: PageBuilder, needed: number): boolean {
  if (p.y + needed > PAGE_H - BODY_BOTTOM) return false;
  return true;
}

function row(p: PageBuilder, cells: string[], widths: number[], opts: { bold?: boolean; bg?: string; size?: number } = {}) {
  const size = opts.size ?? 8;
  const rowH = size + 6;
  if (opts.bg) {
    p.raw(`${opts.bg} rg ${MARGIN_X} ${PAGE_H - p.y - 4} ${widths.reduce((a, b) => a + b, 0)} ${rowH} re f`);
  }
  let x = MARGIN_X + 4;
  cells.forEach((c, i) => {
    p.text(BLACK, opts.bold ? 'F2' : 'F1', size, x, p.y + size, c);
    x += widths[i];
  });
  p.y += rowH;
}

// Summary card with two columns of label/value pairs
function summaryCard(p: PageBuilder, items: Array<[string, string, string?]>) {
  const cardH = Math.ceil(items.length / 2) * 18 + 16;
  ensureSpace(p, cardH + 8);
  // Light grey card background
  p.raw(`${GREY_LIGHT} rg ${MARGIN_X} ${PAGE_H - p.y - cardH} ${PAGE_W - MARGIN_X * 2} ${cardH} re f`);
  // Amber left rule
  p.raw(`${AMBER} rg ${MARGIN_X} ${PAGE_H - p.y - cardH} 3 ${cardH} re f`);
  const colW = (PAGE_W - MARGIN_X * 2 - 16) / 2;
  items.forEach((it, i) => {
    const col = i % 2;
    const rowIdx = Math.floor(i / 2);
    const x = MARGIN_X + 12 + col * colW;
    const y = p.y + 14 + rowIdx * 18;
    const valueColor = it[2] ?? BLACK;
    p.text(GREY_MID, 'F1', 7, x, y - 4, it[0].toUpperCase());
    p.text(valueColor, 'F2', 10, x, y + 7, it[1]);
  });
  p.y += cardH + 8;
}

function paragraph(p: PageBuilder, text: string, size = 8, color = GREY_MID) {
  ensureSpace(p, size + 6);
  p.text(color, 'F1', size, MARGIN_X, p.y + size, text);
  p.y += size + 6;
}

// ── Multi-page rendering ──────────────────────────────────────────────────
type Section = (p: PageBuilder, addPage: () => void) => void;

function renderPages(sections: Section[], header: Parameters<typeof drawHeader>[1]): { contents: string[] } {
  const pages: PageBuilder[] = [];
  let current: PageBuilder;

  const addPage = () => {
    current = new PageBuilder();
    drawHeader(current, header);
    pages.push(current);
  };

  addPage();

  // Wrap ensureSpace logic: if a section runs out of space, callers call addPage.
  for (const section of sections) {
    section(current!, () => addPage());
    // After each section, the section may have called addPage internally.
    // We need to refresh `current` to the latest page.
    current = pages[pages.length - 1];
  }

  // Footer on every page after content is laid out
  pages.forEach((pg, i) => drawFooter(pg, i + 1, pages.length));

  return { contents: pages.map(pg => pg.finalize()) };
}

// Build a paginated table that auto-overflows to new pages.
function tableSection(opts: {
  title: string;
  headers: string[];
  widths: number[];
  rows: string[][];
  emptyMessage: string;
}) {
  const { title, headers, widths, rows, emptyMessage } = opts;
  return (p: PageBuilder, addPage: () => void) => {
    let cur = p;
    sectionTitle(cur, title);
    if (rows.length === 0) {
      paragraph(cur, emptyMessage, 9, GREY_MID);
      cur.y += 4;
      return;
    }
    // Header row
    row(cur, headers, widths, { bold: true, bg: GREY_LIGHT, size: 8 });
    let alt = false;
    for (const r of rows) {
      if (cur.y + 14 > PAGE_H - BODY_BOTTOM) {
        addPage();
        cur = (globalThis as any).__pdfPageRef ?? cur; // unused; addPage handled by closure below
      }
      row(cur, r, widths, { bg: alt ? GREY_LIGHT : undefined, size: 8 });
      alt = !alt;
    }
  };
}

// The simple sequential renderer above doesn't easily refresh `current` for
// table overflow. Use a single-pass renderer that tracks pages directly.
function buildPdfBlob(reportTitle: string, header: Parameters<typeof drawHeader>[1], draw: (api: {
  page: PageBuilder;
  newPage: () => PageBuilder;
}) => void): Blob {
  const pages: PageBuilder[] = [];
  let page = new PageBuilder();
  drawHeader(page, header);
  pages.push(page);

  const newPage = () => {
    page = new PageBuilder();
    drawHeader(page, header);
    pages.push(page);
    return page;
  };

  // Provide a Proxy that always points at the current page
  const api = new Proxy({} as any, {
    get(_t, prop) {
      if (prop === 'page') return page;
      if (prop === 'newPage') return newPage;
      return undefined;
    },
  });

  draw({ get page() { return page; }, newPage } as any);

  pages.forEach((pg, i) => drawFooter(pg, i + 1, pages.length));

  return assemblePdf(pages.map(p => p.finalize()));
}

function assemblePdf(contents: string[]): Blob {
  // All content is ASCII after clean(), so byte-length === string-length.
  // Use TextEncoder for byte-accurate length to be safe if that ever changes.
  const enc = new TextEncoder();
  const byteLen = (s: string) => enc.encode(s).length;

  const objs: string[] = [];
  objs.push('1 0 obj<</Type/Catalog/Pages 2 0 R>>endobj');
  const pageObjStart = 5;
  const refs = contents.map((_, i) => `${pageObjStart + i} 0 R`).join(' ');
  objs.push(`2 0 obj<</Type/Pages/Kids[${refs}]/Count ${contents.length}>>endobj`);
  objs.push('3 0 obj<</Type/Font/Subtype/Type1/BaseFont/Helvetica>>endobj');
  objs.push('4 0 obj<</Type/Font/Subtype/Type1/BaseFont/Helvetica-Bold>>endobj');

  contents.forEach((_c, i) => {
    const streamId = pageObjStart + contents.length + i;
    objs.push(`${pageObjStart + i} 0 obj<</Type/Page/Parent 2 0 R/MediaBox[0 0 ${PAGE_W} ${PAGE_H}]/Contents ${streamId} 0 R/Resources<</Font<</F1 3 0 R/F2 4 0 R>>>>>>endobj`);
  });
  contents.forEach((c, i) => {
    const id = pageObjStart + contents.length + i;
    objs.push(`${id} 0 obj<</Length ${byteLen(c)}>>stream\n${c}endstream\nendobj`);
  });

  let pdf = '%PDF-1.4\n';
  const offsets: number[] = [];
  for (const obj of objs) {
    offsets.push(byteLen(pdf));
    pdf += obj + '\n';
  }
  const xrefPos = byteLen(pdf);
  pdf += `xref\n0 ${objs.length + 1}\n0000000000 65535 f \n`;
  for (const o of offsets) pdf += `${String(o).padStart(10, '0')} 00000 n \n`;
  pdf += `trailer<</Size ${objs.length + 1}/Root 1 0 R>>\nstartxref\n${xrefPos}\n%%EOF`;

  return new Blob([pdf], { type: 'application/pdf' });
}

// ── Public API ────────────────────────────────────────────────────────────
export function buildReportPdf(type: ReportType, agg: ReportAggregation): Blob {
  const reportTitle = REPORT_TYPE_LABELS[type];
  const header = {
    reportTitle,
    rangeLabel: `${agg.range.from} to ${agg.range.to} (${agg.range.label})`,
    generated: format(new Date(), 'yyyy-MM-dd'),
    preparedFor: agg.preparedFor,
  };

  return buildPdfBlob(reportTitle, header, ({ page, newPage }) => {
    let p = page;

    // Empty-state
    if (agg.isEmpty) {
      sectionTitle(p, 'No Data In Range');
      paragraph(p, 'No loads, expenses, or fuel logs were found for this date range.', 10, BLACK);
      return;
    }

    const wantsLoads = type !== 'expense' && type !== 'fuel' && type !== 'tax_estimate';
    const wantsExpenses = type === 'full_profit' || type === 'expense' || type === 'year_end_tax';
    const wantsFuel = type === 'full_profit' || type === 'fuel' || type === 'year_end_tax' || type === 'mileage';
    const wantsTax = type === 'full_profit' || type === 'tax_estimate' || type === 'year_end_tax';

    // ── Executive Summary ───────────────────────────────────────────────
    sectionTitle(p, 'Executive Summary');
    summaryCard(p, [
      ['Total Gross Pay', money(agg.profit.grossRevenue)],
      ['Total Loads', String(agg.summary.loadCount)],
      ['Total Miles', intStr(agg.summary.totalMiles)],
      ['Loaded Miles', intStr(agg.summary.loadedMiles)],
      ['Deadhead Miles', intStr(agg.summary.deadheadMiles)],
      ['Fuel Cost', money(agg.profit.fuelCost)],
      ['Other Expenses', money(agg.profit.expensesTotal)],
      ['Est. Tax Reserve', money(agg.profit.estimatedTaxReserve)],
      ['Net After Expenses', money(agg.profit.netAfterExpenses), agg.profit.netAfterExpenses >= 0 ? GREEN : RED],
      ['Net After Est. Tax', money(agg.profit.netAfterTax), agg.profit.netAfterTax >= 0 ? GREEN : RED],
      ['Profit / Mile', money(agg.profit.profitPerMile)],
      ['Avg Pay / Load', money(agg.profit.avgPayPerLoad)],
    ]);

    const ensure = (need: number) => {
      if (p.y + need > PAGE_H - BODY_BOTTOM) p = newPage();
    };
    const drawRow = (cells: string[], widths: number[], o: Parameters<typeof row>[3] = {}) => {
      ensure(16);
      row(p, cells, widths, o);
    };

    // ── Loads ───────────────────────────────────────────────────────────
    if (wantsLoads) {
      ensure(40);
      sectionTitle(p, 'Load Breakdown');
      const widths = [60, 100, 100, 50, 50, 70, 70];
      drawRow(['Date', 'Pickup', 'Dropoff', 'Loaded', 'DH', 'Est Pay', 'Actual'], widths, { bold: true, bg: GREY_LIGHT });
      let alt = false;
      if (agg.loads.length === 0) {
        paragraph(p, 'No loads in this date range.');
      } else {
        for (const l of agg.loads) {
          drawRow([
            getEffectiveDate(l),
            clean(l.pickup_location, 22),
            clean(l.dropoff_location, 22),
            intStr(Number(l.loaded_miles)),
            intStr(Number(l.deadhead_miles)),
            money(getLoadExpectedPay(l)),
            l.actual_pay_received != null ? money(Number(l.actual_pay_received)) : '—',
          ], widths, { bg: alt ? GREY_LIGHT : undefined });
          alt = !alt;
        }
      }
    }

    // ── Fuel ────────────────────────────────────────────────────────────
    if (wantsFuel) {
      ensure(40);
      sectionTitle(p, 'Fuel Breakdown');
      const widths = [70, 130, 60, 70, 80, 80];
      drawRow(['Date', 'Station', 'Gallons', 'Price/Gal', 'Total', 'Odometer'], widths, { bold: true, bg: GREY_LIGHT });
      if (agg.fuelLogs.length === 0) {
        paragraph(p, 'No fuel logs in this date range.');
      } else {
        let alt = false;
        for (const f of agg.fuelLogs) {
          drawRow([
            f.date,
            clean(f.station ?? '—', 30),
            Number(f.gallons).toFixed(2),
            money(Number(f.price_per_gallon)),
            money(Number(f.total_cost)),
            f.odometer != null ? intStr(Number(f.odometer)) : '—',
          ], widths, { bg: alt ? GREY_LIGHT : undefined });
          alt = !alt;
        }
        drawRow(['Totals', '', agg.fuel.totalGallons.toFixed(2), money(agg.fuel.avgPricePerGallon), money(agg.fuel.totalCost), ''], widths, { bold: true, bg: GREY_LIGHT });
      }
    }

    // ── Expenses ────────────────────────────────────────────────────────
    if (wantsExpenses) {
      ensure(40);
      sectionTitle(p, 'Expense Breakdown');
      const widths = [70, 140, 80, 80];
      drawRow(['Date', 'Category', 'Type', 'Amount'], widths, { bold: true, bg: GREY_LIGHT });
      if (agg.expenses.length === 0) {
        paragraph(p, 'No expenses in this date range.');
      } else {
        let alt = false;
        for (const e of agg.expenses) {
          drawRow([
            e.expense_date,
            clean(e.category, 32),
            (e as any).expense_type ?? '—',
            money(Number(e.amount)),
          ], widths, { bg: alt ? GREY_LIGHT : undefined });
          alt = !alt;
        }
        drawRow(['', 'Total', '', money(agg.profit.expensesTotal)], widths, { bold: true, bg: GREY_LIGHT });
      }
    }

    // ── Tax Estimate ────────────────────────────────────────────────────
    if (wantsTax) {
      ensure(60);
      sectionTitle(p, 'Tax Estimate');
      if (!agg.tax.enabled) {
        paragraph(p, 'Tax estimator is not enabled in your HaulTrackerPro settings.');
      } else {
        const widths = [200, 120];
        drawRow(['Component', 'Amount'], widths, { bold: true, bg: GREY_LIGHT });
        drawRow([`Self-Employment Tax`, money(agg.tax.seTax)], widths);
        drawRow([`Federal Income Tax`, money(agg.tax.federalTax)], widths);
        drawRow([`State Income Tax`, money(agg.tax.stateTax)], widths);
        drawRow([`Buffer`, money(agg.tax.bufferTax)], widths);
        drawRow([`Total Estimated Tax (${agg.tax.baseLabel} basis)`, money(agg.tax.totalTax)], widths, { bold: true, bg: GREY_LIGHT });
        drawRow([`Profit After Est. Tax`, money(agg.tax.profitAfterTax)], widths, { bold: true });
      }
      paragraph(p, TAX_DISCLAIMER, 7, GREY_MID);
    }

    // ── Profit Per Mile recap ───────────────────────────────────────────
    ensure(40);
    sectionTitle(p, 'Profit Per Mile');
    summaryCard(p, [
      ['Net After Expenses', money(agg.profit.netAfterExpenses), agg.profit.netAfterExpenses >= 0 ? GREEN : RED],
      ['Net After Est. Tax', money(agg.profit.netAfterTax), agg.profit.netAfterTax >= 0 ? GREEN : RED],
      ['Profit / Mile', money(agg.profit.profitPerMile)],
      ['Total Miles', intStr(agg.summary.totalMiles)],
    ]);
  });
}

export function downloadPdfBlob(filename: string, blob: Blob) {
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  a.click();
  URL.revokeObjectURL(url);
}
