import type { ReportAggregation, ReportType } from '@/lib/reportAggregator';
import { REPORT_TYPE_LABELS } from '@/lib/reportAggregator';
import { TAX_DISCLAIMER } from '@/lib/reportTax';
import { getEffectiveDate } from '@/lib/loadUtils';
import { getLoadExpectedPay, getLoadOperatingMiles } from '@/lib/loadMetrics';

const esc = (v: string | number | null | undefined): string => {
  const s = v == null ? '' : String(v);
  return /[",\n]/.test(s) ? `"${s.replace(/"/g, '""')}"` : s;
};
const money = (n: number) => (Number.isFinite(n) ? n.toFixed(2) : '0.00');
const num = (n: number) => (Number.isFinite(n) ? String(Math.round(n)) : '0');

function row(...cells: (string | number | null | undefined)[]) {
  return cells.map(esc).join(',');
}

export function buildReportCSV(type: ReportType, agg: ReportAggregation): string {
  const lines: string[] = [];
  const title = REPORT_TYPE_LABELS[type];

  // Header / meta
  lines.push(row(`HaulTrackerPro — ${title}`));
  lines.push(row(`Date Range`, `${agg.range.from} to ${agg.range.to}`));
  lines.push(row(`Generated`, new Date().toISOString().slice(0, 10)));
  lines.push(row(`Prepared For`, agg.preparedFor));
  lines.push('');

  // Executive summary (always)
  lines.push(row('EXECUTIVE SUMMARY'));
  lines.push(row('Total Loads', agg.summary.loadCount));
  lines.push(row('Total Gross Pay', money(agg.profit.grossRevenue)));
  lines.push(row('Total Miles', num(agg.summary.totalMiles)));
  lines.push(row('Loaded Miles', num(agg.summary.loadedMiles)));
  lines.push(row('Deadhead Miles', num(agg.summary.deadheadMiles)));
  lines.push(row('Fuel Cost', money(agg.profit.fuelCost)));
  lines.push(row('Other Expenses', money(agg.profit.expensesTotal)));
  lines.push(row('Estimated Tax Reserve', money(agg.profit.estimatedTaxReserve)));
  lines.push(row('Net After Expenses', money(agg.profit.netAfterExpenses)));
  lines.push(row('Net After Est. Tax', money(agg.profit.netAfterTax)));
  lines.push(row('Profit Per Mile', money(agg.profit.profitPerMile)));
  lines.push(row('Avg Pay Per Load', money(agg.profit.avgPayPerLoad)));
  lines.push('');

  const wantsLoads = type !== 'expense' && type !== 'fuel' && type !== 'tax_estimate';
  const wantsExpenses = type === 'full_profit' || type === 'weekly_performance' || type === 'expense' || type === 'year_end_tax';
  const wantsFuel = type === 'full_profit' || type === 'weekly_performance' || type === 'fuel' || type === 'year_end_tax' || type === 'mileage';
  const wantsTax = type === 'full_profit' || type === 'tax_estimate' || type === 'year_end_tax';

  if (wantsLoads) {
    lines.push(row('LOADS'));
    lines.push(row('Date', 'Pickup', 'Dropoff', 'Loaded Mi', 'DH Mi', 'Total Mi', 'Pay Model', 'Estimated Pay', 'Actual Pay', 'Status', 'Notes'));
    for (const l of agg.loads) {
      lines.push(row(
        getEffectiveDate(l),
        l.pickup_location,
        l.dropoff_location,
        l.loaded_miles,
        l.deadhead_miles,
        getLoadOperatingMiles(l),
        (l as any).pay_model ?? 'loaded_miles_only',
        money(getLoadExpectedPay(l)),
        l.actual_pay_received != null ? money(Number(l.actual_pay_received)) : '',
        l.status ?? 'completed',
        l.notes ?? '',
      ));
    }
    lines.push('');
  }

  if (wantsExpenses) {
    lines.push(row('EXPENSES'));
    lines.push(row('Date', 'Category', 'Type', 'Amount', 'Notes'));
    for (const e of agg.expenses) {
      lines.push(row(e.expense_date, e.category, (e as any).expense_type ?? '', money(Number(e.amount)), (e as any).notes ?? ''));
    }
    lines.push('');
  }

  if (wantsFuel) {
    lines.push(row('FUEL'));
    lines.push(row('Date', 'Station', 'Gallons', 'Price/Gal', 'Total Cost', 'Odometer', 'Notes'));
    for (const f of agg.fuelLogs) {
      lines.push(row(f.date, f.station ?? '', f.gallons, money(Number(f.price_per_gallon)), money(Number(f.total_cost)), f.odometer ?? '', f.notes ?? ''));
    }
    lines.push(row('Totals', '', agg.fuel.totalGallons.toFixed(2), money(agg.fuel.avgPricePerGallon), money(agg.fuel.totalCost), '', ''));
    lines.push('');
  }

  if (wantsTax) {
    lines.push(row('TAX ESTIMATE'));
    if (!agg.tax.enabled) {
      lines.push(row('Tax estimator is not enabled in your settings.'));
    } else {
      lines.push(row('Base', agg.tax.baseLabel));
      lines.push(row('Self-Employment Tax', money(agg.tax.seTax)));
      lines.push(row('Federal Income Tax', money(agg.tax.federalTax)));
      lines.push(row('State Income Tax', money(agg.tax.stateTax)));
      lines.push(row('Buffer', money(agg.tax.bufferTax)));
      lines.push(row('Total Estimated Tax', money(agg.tax.totalTax)));
      lines.push(row('Profit After Est. Tax', money(agg.tax.profitAfterTax)));
    }
    lines.push(row(TAX_DISCLAIMER));
    lines.push('');
  }

  lines.push(row('Generated by HaulTrackerPro — haultrackerpro.com'));
  return lines.join('\n');
}

export function downloadCSV(filename: string, csv: string) {
  const blob = new Blob([csv], { type: 'text/csv;charset=utf-8' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  a.click();
  URL.revokeObjectURL(url);
}
