project_id = "pngptztxwbtozwxrtbwo"

[functions]
  [functions.admin-api]
    verify_jwt = false
  [functions.ai-insight]
    verify_jwt = false
  [functions.auth-email-hook]
    verify_jwt = false
  [functions.check-pro-access]
    verify_jwt = false
  [functions.check-subscription]
    verify_jwt = false
  [functions.create-checkout]
    verify_jwt = false
  [functions.customer-portal]
    verify_jwt = false
  [functions.delete-account]
    verify_jwt = false
  [functions.generate-recurring-expenses]
    verify_jwt = false
  [functions.process-email-queue]
    verify_jwt = true
  [functions.stripe-webhook]
    verify_jwt = false
