project_id = "pngptztxwbtozwxrtbwo"

[functions.create-checkout]
verify_jwt = false

[functions.check-subscription]
verify_jwt = false

[functions.customer-portal]
verify_jwt = false

[functions.admin-api]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false

[functions.check-pro-access]
verify_jwt = false

[functions.delete-account]
verify_jwt = false