import type { RecruiterReportData, RecruiterReportType } from './aggregator';
import { REPORT_TYPE_LABEL } from './aggregator';

const esc = (v: string | number | null | undefined): string => {
  const s = v == null ? '' : String(v);
  return /[",\n]/.test(s) ? `"${s.replace(/"/g, '""')}"` : s;
};
const row = (...cells: (string | number | null | undefined)[]) => cells.map(esc).join(',');
const blank = () => '';
const labelStatus = (s: string) => s.replace(/_/g, ' ').replace(/\b\w/g, c => c.toUpperCase());

export function buildRecruiterReportCSV(type: RecruiterReportType, data: RecruiterReportData): string {
  const lines: string[] = [];
  const title = REPORT_TYPE_LABEL[type];
  // Phase RC-1H — staff output never reveals plan/billing/entitlement state.
  const isStaff = data.header.audience === 'staff';

  lines.push(row(`HaulTrackerPro — ${title}`));
  lines.push(row('Website', 'haultrackerpro.com'));
  lines.push(row('Company', data.header.companyName));
  lines.push(row('Recruiter', data.header.recruiterName));
  lines.push(row('Date Range', `${data.range.from} to ${data.range.to}`));
  lines.push(row('Generated', data.generatedAt));
  if (!isStaff) {
    lines.push(row('Plan', labelStatus(data.header.plan)));
    lines.push(row('Billing Status', labelStatus(data.header.planStatus)));
    lines.push(row('Standard Posting', 'Unlimited after verification'));
    lines.push(row('Premium Tools', data.header.plan === 'growth' || data.header.plan === 'fleet' ? 'Active' : 'Upgrade to Growth'));
    lines.push(row('Priority Placement', data.header.plan === 'growth' || data.header.plan === 'fleet' ? 'Included' : 'Upgrade to Growth'));
  }
  lines.push(blank());


  lines.push(row('EXECUTIVE SUMMARY'));
  lines.push(row('Metric', 'Value'));
  lines.push(row('Active Opportunities', data.kpis.activeOpportunities));
  lines.push(row('Total Applications (in range)', data.kpis.totalApplications));
  lines.push(row('Interviews', data.kpis.interviews));
  lines.push(row('Offers Sent', data.kpis.offersSent));
  lines.push(row('Hired', data.kpis.hired));
  lines.push(row('Rejected', data.kpis.rejected));
  lines.push(row('Withdrawn', data.kpis.withdrawn));
  lines.push(row('Contact Requests', data.contactRequests.total));
  lines.push(blank());

  lines.push(row('APPLICATIONS BY STATUS'));
  lines.push(row('Status', 'Count'));
  data.applicationsByStatus.forEach(s => lines.push(row(labelStatus(s.status), s.count)));
  lines.push(blank());

  lines.push(row('CONTACT REQUESTS BY STATUS'));
  lines.push(row('Status', 'Count'));
  data.contactRequests.byStatus.forEach(s => lines.push(row(labelStatus(s.status), s.count)));
  lines.push(blank());

  lines.push(row('CONTRACT STATUS SUMMARY'));
  lines.push(row('Status', 'Count'));
  data.contractStatusSummary.forEach(s => lines.push(row(labelStatus(s.status), s.count)));
  lines.push(blank());

  if (data.opportunitiesBlockedByContract.length > 0) {
    lines.push(row('OPPORTUNITIES BLOCKED BY CONTRACT'));
    lines.push(row('Application ID', 'Opportunity', 'Application Status', 'Contract Status'));
    data.opportunitiesBlockedByContract.forEach(b =>
      lines.push(row(b.applicationId, b.opportunityTitle, labelStatus(b.applicationStatus), labelStatus(b.contractStatus)))
    );
    lines.push(blank());
  }

  if (type === 'activity') {
    lines.push(row('TOP-PERFORMING OPPORTUNITIES'));
    lines.push(row('Title', 'Applications', 'View Count'));
    data.topOpportunities.forEach(t => lines.push(row(t.title, t.applications, t.viewCount)));
    lines.push(blank());
  } else {
    lines.push(row('PIPELINE BY OPPORTUNITY'));
    lines.push(row('Title', 'Status', 'Applications', 'Interviews', 'Offers', 'Hired', 'Rejected', 'Withdrawn', 'Contract Blocked', 'View Count'));
    data.pipeline.forEach(p =>
      lines.push(row(
        p.title, labelStatus(p.status),
        p.applications, p.interviews, p.offers, p.hired, p.rejected, p.withdrawn,
        p.contractBlocked, p.viewCount
      ))
    );
    lines.push(blank());
  }

  lines.push(row('DISCLAIMER'));
  lines.push(row('Generated from recruiter-owned data only. Does not include any driver financial, load, expense, fuel, profit, or tax information.'));
  lines.push(blank());
  lines.push(row('Generated by HaulTrackerPro — haultrackerpro.com'));

  return lines.join('\n');
}

export function downloadCSV(filename: string, csv: string) {
  const blob = new Blob(['\uFEFF', csv], { type: 'text/csv;charset=utf-8' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  a.click();
  URL.revokeObjectURL(url);
}
