import type { jsPDF as JsPDFType } from 'jspdf';
import type { RecruiterReportData, RecruiterReportType } from './aggregator';
import { REPORT_TYPE_LABEL } from './aggregator';

// jsPDF + jspdf-autotable are heavy (~300KB combined). Keep them out of the
// Recruiter Reports panel chunk and only load them when the user actually
// generates a PDF.

const PRIMARY: [number, number, number] = [217, 119, 6]; // amber
const INK: [number, number, number] = [17, 24, 39];
const MUTED: [number, number, number] = [107, 114, 128];

type AutoTableFn = (doc: JsPDFType, options: any) => void;

const labelStatus = (s: string) => s.replace(/_/g, ' ').replace(/\b\w/g, c => c.toUpperCase());

function drawHeader(doc: JsPDFType, type: RecruiterReportType, data: RecruiterReportData) {
  doc.setFillColor(PRIMARY[0], PRIMARY[1], PRIMARY[2]);
  doc.rect(0, 0, doc.internal.pageSize.getWidth(), 22, 'F');
  doc.setTextColor(255, 255, 255);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(14);
  doc.text(`HaulTrackerPro — ${REPORT_TYPE_LABEL[type]}`, 14, 14);
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(9);
  doc.text('haultrackerpro.com', doc.internal.pageSize.getWidth() - 14, 14, { align: 'right' });

  doc.setTextColor(INK[0], INK[1], INK[2]);
  doc.setFontSize(10);
  const y = 30;
  doc.setFont('helvetica', 'bold');
  doc.text(data.header.companyName, 14, y);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(MUTED[0], MUTED[1], MUTED[2]);
  doc.text(`Recruiter: ${data.header.recruiterName}`, 14, y + 5);
  doc.text(`Date Range: ${data.range.from} to ${data.range.to}`, 14, y + 10);
  doc.text(`Generated: ${data.generatedAt}`, 14, y + 15);
  // Phase RC-1H — staff output never reveals plan/billing/entitlement state.
  if (data.header.audience === 'staff') {
    return y + 23;
  }
  const isPremium = data.header.plan === 'growth' || data.header.plan === 'fleet';
  doc.text(
    `Plan: ${labelStatus(data.header.plan)} (${labelStatus(data.header.planStatus)})`,
    14, y + 20
  );
  doc.text(
    `Standard posting: Unlimited after verification · Premium tools: ${isPremium ? 'Active' : 'Upgrade to Growth'} · Priority placement: ${isPremium ? 'Included' : 'Upgrade to Growth'}`,
    14, y + 25
  );
  return y + 33;
}


function drawFooter(doc: JsPDFType) {
  const pageCount = doc.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(MUTED[0], MUTED[1], MUTED[2]);
    doc.text(
      'Generated by HaulTrackerPro — haultrackerpro.com',
      doc.internal.pageSize.getWidth() / 2,
      doc.internal.pageSize.getHeight() - 8,
      { align: 'center' }
    );
    doc.text(`Page ${i} of ${pageCount}`, doc.internal.pageSize.getWidth() - 14, doc.internal.pageSize.getHeight() - 8, { align: 'right' });
  }
}

function section(doc: JsPDFType, y: number, title: string): number {
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(11);
  doc.setTextColor(INK[0], INK[1], INK[2]);
  doc.text(title, 14, y);
  return y + 4;
}

export async function buildRecruiterReportPDF(
  type: RecruiterReportType,
  data: RecruiterReportData,
): Promise<Blob> {
  // Dynamic imports — only loaded the first time a recruiter generates a PDF.
  const [{ default: JsPDF }, autoTableMod] = await Promise.all([
    import('jspdf'),
    import('jspdf-autotable'),
  ]);
  const autoTable = (autoTableMod as any).default as AutoTableFn;

  const doc = new JsPDF({ unit: 'mm', format: 'letter' });

  let y = drawHeader(doc, type, data);

  y = section(doc, y, 'Executive Summary');
  autoTable(doc, {
    startY: y,
    head: [['Metric', 'Value']],
    body: [
      ['Active Opportunities', String(data.kpis.activeOpportunities)],
      ['Total Applications (in range)', String(data.kpis.totalApplications)],
      ['Interviews', String(data.kpis.interviews)],
      ['Offers Sent', String(data.kpis.offersSent)],
      ['Hired', String(data.kpis.hired)],
      ['Rejected', String(data.kpis.rejected)],
      ['Withdrawn', String(data.kpis.withdrawn)],
      ['Contact Requests', String(data.contactRequests.total)],
    ],
    headStyles: { fillColor: PRIMARY, textColor: 255 },
    styles: { fontSize: 9 },
    margin: { left: 14, right: 14 },
  });
  y = (doc as any).lastAutoTable.finalY + 8;

  if (data.applicationsByStatus.length > 0) {
    y = section(doc, y, 'Applications by Status');
    autoTable(doc, {
      startY: y,
      head: [['Status', 'Count']],
      body: data.applicationsByStatus.map(s => [labelStatus(s.status), String(s.count)]),
      headStyles: { fillColor: PRIMARY, textColor: 255 },
      styles: { fontSize: 9 },
      margin: { left: 14, right: 14 },
    });
    y = (doc as any).lastAutoTable.finalY + 8;
  }

  if (data.contactRequests.byStatus.length > 0) {
    y = section(doc, y, 'Contact Requests by Status');
    autoTable(doc, {
      startY: y,
      head: [['Status', 'Count']],
      body: data.contactRequests.byStatus.map(s => [labelStatus(s.status), String(s.count)]),
      headStyles: { fillColor: PRIMARY, textColor: 255 },
      styles: { fontSize: 9 },
      margin: { left: 14, right: 14 },
    });
    y = (doc as any).lastAutoTable.finalY + 8;
  }

  if (data.contractStatusSummary.length > 0) {
    y = section(doc, y, 'Contract Status Summary');
    autoTable(doc, {
      startY: y,
      head: [['Status', 'Count']],
      body: data.contractStatusSummary.map(s => [labelStatus(s.status), String(s.count)]),
      headStyles: { fillColor: PRIMARY, textColor: 255 },
      styles: { fontSize: 9 },
      margin: { left: 14, right: 14 },
    });
    y = (doc as any).lastAutoTable.finalY + 8;
  }

  if (data.opportunitiesBlockedByContract.length > 0) {
    y = section(doc, y, 'Opportunities Blocked by Contract Approval');
    autoTable(doc, {
      startY: y,
      head: [['Opportunity', 'Application Status', 'Contract Status']],
      body: data.opportunitiesBlockedByContract.map(b => [
        b.opportunityTitle,
        labelStatus(b.applicationStatus),
        labelStatus(b.contractStatus),
      ]),
      headStyles: { fillColor: PRIMARY, textColor: 255 },
      styles: { fontSize: 9 },
      margin: { left: 14, right: 14 },
    });
    y = (doc as any).lastAutoTable.finalY + 8;
  }

  if (type === 'activity' && data.topOpportunities.length > 0) {
    y = section(doc, y, 'Top-Performing Opportunities');
    autoTable(doc, {
      startY: y,
      head: [['Title', 'Applications', 'Views']],
      body: data.topOpportunities.map(t => [t.title, String(t.applications), String(t.viewCount)]),
      headStyles: { fillColor: PRIMARY, textColor: 255 },
      styles: { fontSize: 9 },
      margin: { left: 14, right: 14 },
    });
    y = (doc as any).lastAutoTable.finalY + 8;
  }

  if (type === 'pipeline' && data.pipeline.length > 0) {
    y = section(doc, y, 'Pipeline by Opportunity');
    autoTable(doc, {
      startY: y,
      head: [['Title', 'Status', 'Apps', 'Intv', 'Offers', 'Hired', 'Rej', 'Wdrw', 'Blocked', 'Views']],
      body: data.pipeline.map(p => [
        p.title, labelStatus(p.status),
        String(p.applications), String(p.interviews), String(p.offers), String(p.hired),
        String(p.rejected), String(p.withdrawn), String(p.contractBlocked), String(p.viewCount),
      ]),
      headStyles: { fillColor: PRIMARY, textColor: 255 },
      styles: { fontSize: 8 },
      margin: { left: 14, right: 14 },
    });
    y = (doc as any).lastAutoTable.finalY + 8;
  }

  if (y > 250) { doc.addPage(); y = 20; }
  doc.setFontSize(8);
  doc.setTextColor(MUTED[0], MUTED[1], MUTED[2]);
  doc.text(
    'Generated from recruiter-owned data only. Does not include any driver financial, load, expense, fuel, profit, or tax information.',
    14, y, { maxWidth: doc.internal.pageSize.getWidth() - 28 }
  );

  drawFooter(doc);

  return doc.output('blob');
}

export function downloadBlob(filename: string, blob: Blob) {
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  a.click();
  URL.revokeObjectURL(url);
}
