// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.26.2";

// src/lib/mcp/tools/list-loads.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z } from "npm:zod@^3.25.76";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.97.0";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv([
    "SUPABASE_PUBLISHABLE_KEY",
    "VITE_SUPABASE_PUBLISHABLE_KEY"
  ]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error(
    "SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required"
  );
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("supabaseForUser requires a verified OAuth token");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/tools/list-loads.ts
var list_loads_default = defineTool({
  name: "list_loads",
  title: "List loads",
  description: "List the signed-in driver's most recent loads, newest first. Optionally filter by load status, payment status, or a load date range (YYYY-MM-DD).",
  inputSchema: {
    limit: z.number().int().min(1).max(100).default(20).describe("Maximum loads to return (1-100)."),
    status: z.string().trim().min(1).optional().describe("Filter by load status, e.g. delivered, en_route, cancelled."),
    payment_status: z.string().trim().min(1).optional().describe("Filter by payment status, e.g. paid, unpaid, overdue, short_paid."),
    from_date: z.string().regex(/^\d{4}-\d{2}-\d{2}$/).optional().describe("Only loads with load_date on or after this date (YYYY-MM-DD)."),
    to_date: z.string().regex(/^\d{4}-\d{2}-\d{2}$/).optional().describe("Only loads with load_date on or before this date (YYYY-MM-DD).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit, status, payment_status, from_date, to_date }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("loads").select(
      "id, load_date, dropoff_date, pickup_location, dropoff_location, loaded_miles, deadhead_miles, rate_per_mile, estimated_pay, actual_pay_received, status, payment_status, broker_name_raw, load_reference"
    ).order("load_date", { ascending: false }).limit(limit ?? 20);
    if (status) query = query.eq("status", status);
    if (payment_status) query = query.eq("payment_status", payment_status);
    if (from_date) query = query.gte("load_date", from_date);
    if (to_date) query = query.lte("load_date", to_date);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const loads = data ?? [];
    return {
      content: [{ type: "text", text: JSON.stringify({ count: loads.length, loads }, null, 2) }],
      structuredContent: { count: loads.length, loads }
    };
  }
});

// src/lib/mcp/tools/list-expenses.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z2 } from "npm:zod@^3.25.76";
var list_expenses_default = defineTool2({
  name: "list_expenses",
  title: "List expenses",
  description: "List the signed-in driver's most recent expenses, newest first. Optionally filter by category or an expense date range (YYYY-MM-DD).",
  inputSchema: {
    limit: z2.number().int().min(1).max(100).default(20).describe("Maximum expenses to return (1-100)."),
    category: z2.string().trim().min(1).optional().describe("Filter by expense category, e.g. Fuel, Maintenance, Insurance."),
    from_date: z2.string().regex(/^\d{4}-\d{2}-\d{2}$/).optional().describe("Only expenses on or after this date (YYYY-MM-DD)."),
    to_date: z2.string().regex(/^\d{4}-\d{2}-\d{2}$/).optional().describe("Only expenses on or before this date (YYYY-MM-DD).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit, category, from_date, to_date }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("expenses").select("id, expense_date, category, expense_type, amount, gallons, notes, linked_load_id").order("expense_date", { ascending: false }).limit(limit ?? 20);
    if (category) query = query.eq("category", category);
    if (from_date) query = query.gte("expense_date", from_date);
    if (to_date) query = query.lte("expense_date", to_date);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const expenses = data ?? [];
    const total = expenses.reduce((sum, row) => sum + Number(row.amount ?? 0), 0);
    return {
      content: [
        { type: "text", text: JSON.stringify({ count: expenses.length, total_amount: total, expenses }, null, 2) }
      ],
      structuredContent: { count: expenses.length, total_amount: total, expenses }
    };
  }
});

// src/lib/mcp/tools/profit-summary.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z3 } from "npm:zod@^3.25.76";
var profit_summary_default = defineTool3({
  name: "profit_summary",
  title: "Profit summary",
  description: "Summarize the signed-in driver's revenue, expenses, net profit, miles, and rate per mile over a date range (YYYY-MM-DD). Cancelled loads are excluded from revenue.",
  inputSchema: {
    from_date: z3.string().regex(/^\d{4}-\d{2}-\d{2}$/).describe("Start of the period (YYYY-MM-DD), inclusive."),
    to_date: z3.string().regex(/^\d{4}-\d{2}-\d{2}$/).describe("End of the period (YYYY-MM-DD), inclusive.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ from_date, to_date }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    if (from_date > to_date) {
      return { content: [{ type: "text", text: "from_date must not be after to_date" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const [loadsResult, expensesResult] = await Promise.all([
      supabase.from("loads").select("estimated_pay, actual_pay_received, loaded_miles, deadhead_miles, status").gte("load_date", from_date).lte("load_date", to_date),
      supabase.from("expenses").select("amount, expense_type").gte("expense_date", from_date).lte("expense_date", to_date)
    ]);
    if (loadsResult.error) {
      return { content: [{ type: "text", text: loadsResult.error.message }], isError: true };
    }
    if (expensesResult.error) {
      return { content: [{ type: "text", text: expensesResult.error.message }], isError: true };
    }
    const loads = (loadsResult.data ?? []).filter((l) => l.status !== "cancelled");
    const revenue = loads.reduce(
      (sum, l) => sum + Number(l.actual_pay_received ?? l.estimated_pay ?? 0),
      0
    );
    const loadedMiles = loads.reduce((sum, l) => sum + Number(l.loaded_miles ?? 0), 0);
    const deadheadMiles = loads.reduce((sum, l) => sum + Number(l.deadhead_miles ?? 0), 0);
    const totalMiles = loadedMiles + deadheadMiles;
    const expenses = expensesResult.data ?? [];
    const totalExpenses = expenses.reduce((sum, e) => sum + Number(e.amount ?? 0), 0);
    const round = (n) => Math.round(n * 100) / 100;
    const summary = {
      from_date,
      to_date,
      load_count: loads.length,
      revenue: round(revenue),
      total_expenses: round(totalExpenses),
      net_profit: round(revenue - totalExpenses),
      loaded_miles: round(loadedMiles),
      deadhead_miles: round(deadheadMiles),
      total_miles: round(totalMiles),
      revenue_per_loaded_mile: loadedMiles > 0 ? round(revenue / loadedMiles) : null,
      deadhead_percent: totalMiles > 0 ? round(deadheadMiles / totalMiles * 100) : null
    };
    return {
      content: [{ type: "text", text: JSON.stringify(summary, null, 2) }],
      structuredContent: summary
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "project-ref-unset";
try {
  projectRef = "pngptztxwbtozwxrtbwo";
} catch {
}
var mcp_default = defineMcp({
  name: "haul-tracker-pro",
  title: "Haul Tracker Pro",
  version: "0.1.0",
  instructions: "Read-only tools for Haul Tracker Pro. Every tool acts as the signed-in driver and returns only that driver's own data. Use `list_loads` for recent loads, `list_expenses` for recent expenses, and `profit_summary` for revenue, expense, mileage, and net-profit totals over a date range.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_loads_default, list_expenses_default, profit_summary_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.26.2/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
